os: osx
language: swift
osx_image: xcode11.3

branches:
  only: 
    - master
stages:
  - lint
  - carthage
  - swiftpm
  - test
jobs:
  include:
    - &pod
      stage: lint
      osx_image: xcode10.2
      env: SWIFT=5.0
      cache:
        - cocoapods
        - directories:
          - Carthage
      before_install:
        gem install cocoapods --version 1.8.4
      install:
        carthage bootstrap --no-build --new-resolver PromiseKit
      script: |
        cd Carthage/Checkouts/PromiseKit
        mv .github/PromiseKit.podspec .
        rm -rf Extensions/Alamofire/Sources
        cp -R ../../../Sources Extensions/Alamofire
        pod lib lint --subspec=PromiseKit/Alamofire --fail-fast --swift-version=$SWIFT
    - <<: *pod
      osx_image: xcode11.0
      env: SWIFT=5.0
    - <<: *pod
      osx_image: xcode11.0
      env: SWIFT=5.1
    - <<: *pod
      osx_image: xcode11.1
      env: SWIFT=5.1
    - <<: *pod
      osx_image: xcode11.2
      env: SWIFT=5.1
    - <<: *pod
      osx_image: xcode11.3
      env: SWIFT=5.1
      
    - &carthage
      stage: carthage
      osx_image: xcode10.2
      script: |
        carthage bootstrap --cache-builds --new-resolver
        sed -i '' "s/SWIFT_TREAT_WARNINGS_AS_ERRORS = NO;/SWIFT_TREAT_WARNINGS_AS_ERRORS = YES;/" *.xcodeproj/project.pbxproj
        carthage build --no-skip-current
      cache.directories:
        - Carthage
    - <<: *carthage
      osx_image: xcode11.0
    - <<: *carthage
      osx_image: xcode11.1
    - <<: *carthage
      osx_image: xcode11.2
    - <<: *carthage
      osx_image: xcode11.3

    - &swiftpm
      stage: swiftpm
      osx_image: xcode8.3
      script: swift build
    - <<: *swiftpm
      osx_image: xcode10.2
    - <<: *swiftpm
      osx_image: xcode11.0
    - <<: *swiftpm
      osx_image: xcode11.1
    - <<: *swiftpm
      osx_image: xcode11.2
    - <<: *swiftpm
      osx_image: xcode11.3

    - &test
      stage: test
      xcode_scheme: PMKAlamofire
      xcode_project: PMKAlamofire.xcodeproj
      xcode_destination: 'platform=macOS'
      cache.directories:
        - Carthage
      before_install:
        carthage bootstrap --cache-builds --new-resolver --no-use-binaries
    - <<: *test
      xcode_destination: 'platform=iOS Simulator,OS=13.3,name=iPhone SE'
    - <<: *test
      xcode_destination: 'platform=tvOS Simulator,OS=13.3,name=Apple TV'
